### ISSUE TITLE
Waiting for the code on the edge my seat :-) 

### ISSUE THREAD

**Issue by urimerhav** [NathanUA/U-2-Net#1]
Hi,

I'm a great fan of your work so far. Your readme states that the code will be released May 4th, has the timeline changed?

Thanks!

**Comment by NathanUA** [comment]
Thanks for you interests. We are sorry for the misleading date info there. That is the time of posting the news. We are currently cleaning our code and hopefully to release it before the end of this week (2020-May-10).

**Comment by vincentzhang** [comment]
Code released
