### ISSUE TITLE
Is it possible to convert the code to keras?

### ISSUE THREAD

**Issue by onesmall228** [NathanUA/U-2-Net#120]
I am a beginner in pytorch and want to switch to keras so that I can understand it more easily. Is this network suitable for writing in keras?

**Comment by NathanUA** [comment]
Someone has converted it to keras: https://github.com/ypeleg/U-2-Net-Keras <https://github.com/ypeleg/U-2-Net-Keras>. Please feel free to try.
Best of luck.

**Comment by onesmall228** [comment]
Thank you so much for the quick reply.
