### ISSUE TITLE
Train issue.

### ISSUE THREAD

**Issue by Joevaen** [NathanUA/U-2-Net#127]
I am trying to train on my custom dataset, when I run u2net_train.py, this happens`ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().) `
I know it happened because there is some problem with labels, my labels is binary .png whose value is 0 or 255. What should I do?

**Comment by Joevaen** [comment]
solved.[https://stackoverflow.com/questions/57517740/pytorch-custom-dataset-valueerror-some-of-the-strides-of-a-given-numpy-array-a](url)

**Comment by akshayklr057** [comment]
@Joevaen Hi, I am facing the same issue with my custom dataset. I have tried the methods from the stackoverflow link you provided as a solution but I'm still getting the same error. Could you please tell me exact changes you incorporated in your code to remove the error?

**Comment by akshayklr057** [comment]
The error is because of flipping the image i.e image[::-1]. I turned it off and it got resolved.

**Comment by yanchaoguo** [comment]
> @Joevaen Hi, I am facing the same issue with my custom dataset. I have tried the methods from the stackoverflow link you provided as a solution but I'm still getting the same error. Could you please tell me exact changes you incorporated in your code to remove the error?

加.copy()
将torch.from_numpy(tmpLbl)  修改为 torch.from_numpy(tmpLbl.copy())

**Comment by syfbme** [comment]
Hi @yanchaoguo @akshayklr057 
I have met the same issue and i have tried both your solutions. The issue was solved but after some training time, there is another issue:
![image](https://user-images.githubusercontent.com/13032160/135236427-74fe9c3a-88d0-4b43-8801-49480d6226ab.png)

Have you ever met this one?

**Comment by prateekchhikara** [comment]
@syfbme I faced the similar issue and I solved it by setting `num_workers = 0` in the following line of `u2net_train.py`

```
salobj_dataloader = DataLoader(salobj_dataset, batch_size=batch_size_train, shuffle=True, num_workers=0)
```
