### ISSUE TITLE
Why do we concatanate and then also sum the outputs before claculating loss?

### ISSUE THREAD

**Issue by shgidi** [NathanUA/U-2-Net#128]
In your diagram, there are 6 "side" outputs, which are then concatanted into a 7th tensor.
Then, in your code the whole 7 outputs are further summed into a final loss.
Isn't there a redundancy of the sum of all outputs and their concatanations?

**Comment by vincentzhang** [comment]
This is the deep supervision described in Section 3.3 of the paper. We cited [HED](https://openaccess.thecvf.com/content_iccv_2015/papers/Xie_Holistically-Nested_Edge_Detection_ICCV_2015_paper.pdf), where you can find more details if you're interested.

The concatenation (7th tensor) is passed through a conv layer which is trained to fuse the predictions from multiple stages. Hence it's not redundant.
