### ISSUE TITLE
dataloader problem

### ISSUE THREAD

**Issue by awzp012** [NathanUA/U-2-Net#129]
I use the images in your_portrait_im and its results as the training set.
  I think the loader has loaded these images because i can get the content:
  ['C:\\Users\\Lcy\\Downloads\\U-2-Net-master\\U-2-Net-master\\train_data\\image\\GalGadot.jpg', 'C:\\Users\\Lcy\\Downloads\\U-2-Net-master\\U-2-Net-master\\train_data\\image\\guliNazha3.jpg', 'C:\\Users\\Lcy\\Downloads\\U-2-Net-master\\U-2-Net-master\\train_data\\image\\kid1.jpg', 'C:\\Users\\Lcy\\Downloads\\U-2-Net-master\\U-2-Net-master\\train_data\\image\\kid2.jpg', 'C:\\Users\\Lcy\\Downloads\\U-2-Net-master\\U-2-Net-master\\train_data\\image\\kid3.jpg', 'C:\\Users\\Lcy\\Downloads\\U-2-Net-master\\U-2-Net-master\\train_data\\image\\man.jpg', 'C:\\Users\\Lcy\\Downloads\\U-2-Net-master\\U-2-Net-master\\train_data\\image\\man2.jpg', 'C:\\Users\\Lcy\\Downloads\\U-2-Net-master\\U-2-Net-master\\train_data\\image\\man4.jpg', 'C:\\Users\\Lcy\\Downloads\\U-2-Net-master\\U-2-Net-master\\train_data\\image\\man5.jpg', 'C:\\Users\\Lcy\\Downloads\\U-2-Net-master\\U-2-Net-master\\train_data\\image\\smile.jpg']
  by print(salobj_dataloader.dataset.image_name_list)
  
  but I got runtime error as following:

 RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "C:\Users\Lcy\anaconda3\envs\python3_7\lib\site-packages\torch\utils\data\dataloader.py", line 872, in _try_get_data
  File "C:\Users\Lcy\anaconda3\envs\python3_7\lib\multiprocessing\queues.py", line 105, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\u2net_train.py", line 127, in <module>
    for i, data in enumerate(salobj_dataloader):
  File "C:\Users\Lcy\anaconda3\envs\python3_7\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\Users\Lcy\anaconda3\envs\python3_7\lib\site-packages\torch\utils\data\dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "C:\Users\Lcy\anaconda3\envs\python3_7\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\Lcy\anaconda3\envs\python3_7\lib\site-packages\torch\utils\data\dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 18168) exited unexpectedly

**Comment by vincentzhang** [comment]
looks like a pytorch problem. What's the pytorch version?

**Comment by awzp012** [comment]
my pytorch version is 1.7.1
And I have sloved this problem this morning，by  following link:

https://github.com/pytorch/pytorch/issues/5858 


Thanks for your response!!

**Comment by KirisameR** [comment]
> 

Hello, how did you managed to solve this issue? Thanks.
