### ISSUE TITLE
Can I specify object to be segmented?

### ISSUE THREAD

**Issue by xamxixixo** [NathanUA/U-2-Net#14]
Hello, thank you for this work.

This issue is as the following images:

![1149](https://user-images.githubusercontent.com/37895275/81711861-e2a09980-9428-11ea-8f19-0a62cfeeb75d.png)
![1150](https://user-images.githubusercontent.com/37895275/81711873-e502f380-9428-11ea-8b11-8c1c02ffc606.png)

Is there a way to choose object to be segmented? Or how do I keep the guitar along the sequence of images?

Thank you.

**Comment by NathanUA** [comment]
That is a good question. Unfortunately, there is no automatic way of choosing to-be-segmented object (detection->segmenation e.g. mask-rcnn).  To keep the prediction consistent, I think you can try to integrate optical flow with the rgb video frames (what video salient object detection methods e.g. SSAV, usually do) and retrain a model to achieve relatively consistent results on videos.

**Comment by xamxixixo** [comment]
Thank you
