### ISSUE TITLE
Merge the Pull requests

### ISSUE THREAD

**Issue by seekingdeep** [NathanUA/U-2-Net#153]
@NathanUA 
i have noticed that you are not merging the Pull requests, some of them are very important to fix the bugs and reduce memory.
did you abandon this repository?

**Comment by NathanUA** [comment]
Thanks for you reminding. We are still maintaining it but we are mainly focus on our new research may not able to response to these PR in time.

**Comment by seekingdeep** [comment]
Thanks,
though pull #112 seems to be very important, it reduces the RAM usage by 50%
