### ISSUE TITLE
Problems related to the training set

### ISSUE THREAD

**Issue by ljc19940403** [NathanUA/U-2-Net#16]
First，appreciate your excellent work！In the training set, I need a little guidance.
In BASNet, you detailed the composition of the training set，In this job, did you use the same training set during training？

**Comment by NathanUA** [comment]
Yes, the training set (DUTS-TR) is the same except for the input size.

**Comment by ljc19940403** [comment]
thank you for your reply！
Because I found in my previous work that training by supplementing a custom data set can continue to improve the detection effect of the model

**Comment by NathanUA** [comment]
I think so. The current u2net model is trained with only DUTS-TR (for the fairness in comparing with other existing models). More dataset should improve the performance more or less.
