### ISSUE TITLE
How are masks created ? maybe out of topic

### ISSUE THREAD

**Issue by cmdrootaccess** [NathanUA/U-2-Net#31]
This is from the DUTS Dataset. just out of curiosity how is such a mask created ? 
![ILSVRC2012_test_00000003](https://user-images.githubusercontent.com/14039016/83000623-458e5500-a013-11ea-9f2e-09bef3a79523.jpg)
![ILSVRC2012_test_00000003](https://user-images.githubusercontent.com/14039016/83000633-46bf8200-a013-11ea-873d-cd387d49d3ba.png)

**Comment by bluesky314** [comment]
some annotation tool like LabelMe or Amazon mechanical turk
