### ISSUE TITLE
About inference speed

### ISSUE THREAD

**Issue by phy12321** [NathanUA/U-2-Net#35]
Thanks for your great job!
From paper I know that U2Net runs at a speed of 30 FPS, with input size of 320×320×3) on a 1080Ti, U2-Net+(4.7 MB) runs at  40 FPS, but on which GPU U2Net running? 1080Ti?

**Comment by NathanUA** [comment]
Both are tested on a NVIDIA gtx 1080 ti GPU.

**Comment by DBraun** [comment]
With the large U2Net model on my RTX 2080, I'm getting about 7 fps (130ms) in my C++ app, making sure the module and input data are on the GPU. I'll keep trying to improve it.

```c++
// in loop for every frame
auto start = high_resolution_clock::now();
auto result = module.forward({ rgb });
auto stop = high_resolution_clock::now();
myDuration = duration_cast<milliseconds>(stop - start);
myDuration.count(); // about 130ms avg when displayed via HUD
```

**Comment by clelouch** [comment]
I've also tried to test the inference speed of U2Net. However, the larger U2Net running at a speed of 16 FPS on RTX TITAN Xp when processing 352X352X3 image. 
`    with torch.no_grad():
        start = time.time()
        res = model(img)
        torch.cuda.synchronize()
        end = time.time()
        # print(res.shape)
        print(end - start)
`
