### ISSUE TITLE
Background Removal for videos

### ISSUE THREAD

**Issue by kashyappiyush1998** [NathanUA/U-2-Net#70]
Is there an efficient method to do background removal on videos? 
Prediction is always on one image, can we process multiple images in one go?

**Comment by i-amgeek** [comment]
Have you tried changing batch size in test loader [here](https://github.com/NathanUA/U-2-Net/blob/master/u2net_test.py#L76) ?

**Comment by kashyappiyush1998** [comment]
But if you look down, actually dataloader is being looped, and prediction is on each image itself. But what if I want to predict on multiple images at once, that would be great.

**Comment by Billy-Mazotti** [comment]
@kashyappiyush1998 Hi! Did you find a solution for creating a video input?
