### ISSUE TITLE
Implements on Android

### ISSUE THREAD

**Issue by arnoldhoward** [NathanUA/U-2-Net#81]
I am very happy to have encountered this amazing model.
I am trying to test this model on an android phone.
I am trying to realize the code in c++, but I am not sure how to do it.
Hope for help.

**Comment by vincentzhang** [comment]
One way is to run the model as a service as in https://github.com/cyrildiagne/basnet-http
Then you can write an android app that calls this service.

**Comment by arnoldhoward** [comment]
Hi, Hathan.
Thanks for your reply.
Yes, you are right, I can make api.
But I’d like to make android app that run u2net on it.
I know you already did it.
Please help me.
Thanks.
Arnold
