### ISSUE TITLE
Feature extraction using u-2-net

### ISSUE THREAD

**Issue by annabeth-h** [NathanUA/U-2-Net#90]
how can I use u-2-net for extracting features of image. Is it enough to just remove the last layer?

**Comment by NathanUA** [comment]
There are seven outputs including the last fusing one. The d1-d6 can be taken as side outputs. To achieve their feature maps, you can try to return hx1d, hx2d, … hx5d and hx6. As for the d0, its the fusion of d1-d6.

**Comment by annabeth-h** [comment]
By "fusion" you mean simple concatenation or you consider any special operation?

**Comment by annabeth-h** [comment]
thank you.So then how can make them a unified feature? Is a simple concatenation enough for that?

**Comment by NathanUA** [comment]
You can simple concatenate them or just use the output hx1d, which has the highest resolution. It depends on what task or purpose of extracting the features.
