### ISSUE TITLE
Pre-trained model dataset ?

### ISSUE THREAD

**Issue by julienguegan** [NathanUA/U-2-Net#94]
Hello,

Please, Can you indicate on which dataset are trained the model given in your readme (those available with a google drive link) ?

Thank you a lot

**Comment by muhammadabdullah34907** [comment]
Although they have mentioned, DUTS dataset. Here is the link.

http://saliencydetection.net/duts/

**Comment by julienguegan** [comment]
they mentionned many dataset in their readme and test their model on all of them but I don't see where they specifically say that the model weights trained on the drive are about DUST ... neither the image size used

**Comment by vincentzhang** [comment]
Please refer to Section 4 of the paper for the dataset and image size along with other training details.
